# Generated by Django 4.2.27 on 2025-12-05 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('inclusion', 'Inclusion'), ('responsabilite', 'Responsabilité'), ('durabilite', 'Durabilité')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name': 'Pilier NIRD',
                'verbose_name_plural': 'Piliers NIRD',
            },
        ),
        migrations.CreateModel(
            name='TechnologyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=50, unique=True, verbose_name='ID Carte')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('card_type', models.CharField(choices=[('big-tech', 'Big Tech'), ('nird', 'NIRD')], max_length=20, verbose_name='Type')),
                ('pillar', models.CharField(choices=[('inclusion', 'Inclusion'), ('responsabilite', 'Responsabilité'), ('durabilite', 'Durabilité')], max_length=20, verbose_name='Pilier')),
                ('description', models.TextField(verbose_name='Description')),
                ('icon', models.CharField(max_length=10, verbose_name='Icône')),
                ('cost', models.CharField(max_length=50, verbose_name='Coût')),
                ('co2', models.CharField(max_length=50, verbose_name='Impact CO2')),
                ('data_location', models.CharField(max_length=100, verbose_name='Localisation données')),
                ('savings_euros', models.IntegerField(default=0, verbose_name='Économies €')),
                ('savings_co2_kg', models.IntegerField(default=0, verbose_name='Économies CO2 (kg)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alternative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternatives', to='cards.technologycard', verbose_name='Alternative')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='cards.category')),
            ],
            options={
                'verbose_name': 'Carte Technologie',
                'verbose_name_plural': 'Cartes Technologies',
                'ordering': ['category', 'name'],
            },
        ),
    ]
